language: node_js

node_js:
    "node"

cache:
  directories:
    - "node_modules"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: dist
  verbose: true
  on:
    branch: master
